# Generated by Django 5.1.3 on 2024-12-01 21:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engTrack', '0002_alter_video_average_engagement_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('done', 'Done')], default='processing', max_length=10),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_upload_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации видео'),
        ),
    ]
