# Generated by Django 5.1.3 on 2024-12-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engTrack', '0003_video_status_alter_video_video_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('done', 'Done'), ('canceled', 'Canceled'), ('pending', 'Pending')], default='processing', max_length=10),
        ),
    ]
