# Generated by Django 5.1.3 on 2024-12-01 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engTrack', '0005_alter_video_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(default=123, upload_to='videos/'),
            preserve_default=False,
        ),
    ]
